### ISSUE TITLE
Host Virtual Environment Unresponsive

### ISSUE THREAD

**Issue by wsisulak** [splunk/attack_range_local#13]
I am trying to run Splunk attack range locally on VirtualBox and as soon as the attack-range-splunk-server starts up my host VirtualBox environment locks up and becomes unresponsive. If it’s a resource issue what system requirements are recommended (hard drive space, memory size, number of CPU’s).

**Comment by kseidenschnur** [comment]
Hi,

I am running my system on a machine with:

6 Cores
16 GB Memory
2000 GB Disk space.

Tested with Splunk Server, Windows DC and Windows Client. As you can imagine the performance is not the best, but it works.
You can also adjust the hardware specs if you like. You will find the configuration in the vagrant folder. Let me know if you have any further questions.


Kai

**Comment by P4T12ICK** [comment]
Thank you for the great answer.
