### ISSUE TITLE
Ubuntu 18.04 Installation Wiki page mistake

### ISSUE THREAD

**Issue by julianwieg** [splunk/attack_range_local#16]
Small copy paste error I assume as I think the AWS install script was copy pasted by accident?
On the install page the initial script has a few error and I think entries that are not needed.
So on page https://github.com/splunk/attack_range_local/wiki/Ubuntu-18.04-Installation

`git clone https://github.com/splunk/attack_range && cd attack_range`
 attack_range**_local**  is correct

`terraform`   commands are not needed/does not exist in _local   (vagrant does but vagrant does not require initialization it seems)

FYI on 18.04  Desktop git is not included so you could add it to the apt-get install packages as a dependency.

But this is much easier then the article I have written in Q1 this year 👍

**Comment by P4T12ICK** [comment]
done. Thank you very much
