### ISSUE TITLE
Typo in stat for CIM App

### ISSUE THREAD

**Issue by malvidin** [splunk/attack_range_local#24]
https://github.com/splunk/attack_range_local/blob/cbbb06c2f861b17022807b771f86d262dbfb0fd4/ansible/roles/search_head/tasks/install_cim_app.yml#L3

On line 3, the stat value is incorrect, it should be the same as the other lines in this file.
Splunk_SA_CIM

**Comment by patel-bhavin** [comment]
@malvidin : thank you for reporting this issue. Will get this fixed!

**Comment by malvidin** [comment]
I believe that it is case sensitive, and should be SA_CIM, not SA_cim

**Comment by patel-bhavin** [comment]
oh yes, my build failed with that!  good eye :)
