### ISSUE TITLE
Windows Domain Controller Fails to Build - guest machine invalid state - gurumeditation

### ISSUE THREAD

**Issue by forensic65x** [splunk/attack_range_local#29]
Host: MacOS Big Sur - Version 11.1 (i9, 32GB Memory)
Virtual Environment: Vmware Fusion Pro 12
Guest: Ubuntu 18.04 LTS (8 cores, 16GB Memory)
Error below:

PLAY RECAP *********************************************************************
attack-range-splunk-server : ok=62   changed=8    unreachable=0    failed=0    skipped=77   rescued=0    ignored=0   

==> attack-range-windows-domain-controller: Checking if box 'd1vious/windows2016' version '1.0' is up to date...
==> attack-range-windows-domain-controller: Clearing any previously set forwarded ports...
==> attack-range-windows-domain-controller: Fixed port collision for 22 => 2222. Now on port 2200.
==> attack-range-windows-domain-controller: Clearing any previously set network interfaces...
==> attack-range-windows-domain-controller: Preparing network interfaces based on configuration...
    attack-range-windows-domain-controller: Adapter 1: nat
    attack-range-windows-domain-controller: Adapter 2: hostonly
==> attack-range-windows-domain-controller: Forwarding ports...
    attack-range-windows-domain-controller: 3389 (guest) => 3389 (host) (adapter 1)
    attack-range-windows-domain-controller: 22 (guest) => 2200 (host) (adapter 1)
    attack-range-windows-domain-controller: 5985 (guest) => 6000 (host) (adapter 1)
    attack-range-windows-domain-controller: 5985 (guest) => 55985 (host) (adapter 1)
    attack-range-windows-domain-controller: 5986 (guest) => 55986 (host) (adapter 1)
==> attack-range-windows-domain-controller: Running 'pre-boot' VM customizations...
==> attack-range-windows-domain-controller: Booting VM...
==> attack-range-windows-domain-controller: Waiting for machine to boot. This may take a few minutes...
    attack-range-windows-domain-controller: WinRM address: 127.0.0.1:6000
    attack-range-windows-domain-controller: WinRM username: vagrant
    attack-range-windows-domain-controller: WinRM execution_time_limit: PT2H
    attack-range-windows-domain-controller: WinRM transport: plaintext
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'gurumeditation' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
2020-12-30 14:39:53,246 - ERROR - attack_range - vagrant failed to build

**Comment by P4T12ICK** [comment]
Hello, I can't reproduce your issue. I use MacOS Big Sur, VirtualBox Version 6.1.16 r140961 (Qt5.6.3), Vagrant 2.2.14.
Maybe try to completely delete the virtual machines before trying it again.

**Comment by forensic65x** [comment]
I was able to reproduce it.  I deleted the entire environment 3 times and received the same error on each new attempt.

What OS was your vagrant running on?

Did you have a Guest OS running on your MacOS that you were building the VMs from, or were you creating the VMs directly on your MacOS?

To confirm, here's my environment:

MacOS Big Sur => VMWare Fusion Pro 12 => Unbuntu 18.04 VM => VirtualBox => Attack Range VMs

**Comment by P4T12ICK** [comment]
Hi, sorry for the late reply. My environment stack is the following:
MacOS Big Sur => VirtualBox 6.1.16 r140961 => Attack Range VMs

The VMs are directly created in VirtualBox by vagrant.

**Comment by forensic65x** [comment]
It appears the issue is related to my attempt to create the Attack Range VMs inside the virtual Ubuntu environment running on my Mac.

To give some background.. I give free cyber training courses and I was attempting to create the VMs in a Ubuntu guest so the students could replicate the steps on their Windows laptops.
