### ISSUE TITLE
HELP WITH CUSTOMCONFIGPARSER MODULE

### ISSUE THREAD

**Issue by pkamal227** [splunk/attack_range_local#32]
Trying to build attack range locally getting following error even though i have the module in the path site-package

(venv) ron@ron-VirtualBox:~/Desktop/attack_range_local$ which python
/home/ron/Desktop/attack_range_local/venv/bin/python
(venv) ron@ron-VirtualBox:~/Desktop/attack_range_local$ export PATH=$PATH:~^C
(venv) ron@ron-VirtualBox:~/Desktop/attack_range_local$ export PATH=$PATH:~/home/ron/Desktop/attack_range_local/venv/bin/python
(venv) ron@ron-VirtualBox:~/Desktop/attack_range_local$ export PYTHONPATH=$PYTHONPATH:/home/ron/Desktop/attack_range_local/venv/lib/python2.7/site-packages/

(venv) ron@ron-VirtualBox:~/Desktop/attack_range_local$ python attack_range_local.py -a build
Traceback (most recent call last):
  File "attack_range_local.py", line 10, in <module>
    from modules.CustomConfigParser import CustomConfigParser

please help how to get pass this module?

**Comment by kseidenschnur** [comment]
Hi, I guess you were following the installations instructions?
The module CustomConfigParser is being loaded out of the attack_range_local/modules/ folder.
