### ISSUE TITLE
"Linux endpoint" referred to in image in Readme doesnt exist in project files 

### ISSUE THREAD

**Issue by ezzeldinadel** [splunk/attack_range_local#34]
"Linux endpoint" referred to in image in Readme doesnt exist in project files. Instead there is a windows10 workstation.

**Comment by kseidenschnur** [comment]
Hi, that is correct. But the Readme also states that these clients are currently under development. Sorry of the confusion here.

**Comment by P4T12ICK** [comment]
We have this done in Attack Range. We need still to migrate it to Attack Range Local.

**Comment by pyth0n1c** [comment]
Closing this issue as Attack Range Local has been deprecated (and functionality migrated into Attack Range).  Please use [https://github.com/splunk/attack_range](https://github.com/splunk/attack_range) for all future simulation needs.
