### ISSUE TITLE
Could not find the requested service splunk: host - attack_range_local

### ISSUE THREAD

**Issue by pud99** [splunk/attack_range_local#36]
Hello team,

PFA

![Screenshot (502)](https://user-images.githubusercontent.com/41522680/108756442-84374880-756e-11eb-8030-0530cd898ae7.png)

Even before this error, splunk package was unable to download automatically so, I manually downloaded and extracted the tar file and then it doesnt get past this step.

**Comment by pud99** [comment]
Hello team,

Can someone please update me on this issue?

**Comment by P4T12ICK** [comment]
Hi @pud99, sorry for my late reply. Does this issue still exists? The Attack Range Local is not designed that you download it manually. I would suggest we fix the download issue.

**Comment by d1vious** [comment]
@pud99 are you still having the same issue, this seemed to be specific to your environment if is not able to download. Feel free to reply to this message to reopen the issue if anything.
