### ISSUE TITLE
Installation failing at set-timezone .yml

### ISSUE THREAD

**Issue by charlesbinny21arockia** [splunk/attack_range_local#41]
My installation is breaking down  as its failing at the  one of the  ansible task. Please find the error message i am getting.

==> attack-range-windows-domain-controller: Checking if box 'd1vious/windows2016' version '1.0' is up to date...
==> attack-range-windows-domain-controller: Running provisioner: ansible...
    attack-range-windows-domain-controller: Running ansible-playbook...
ERROR! couldn't resolve module/action 'community.windows.win_timezone'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/Users/charlesbinny/attack_range_local/ansible/roles/windows_common/tasks/set-timezone.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Set timezone
  ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
2021-04-12 23:12:12,256 - ERROR - attack_range - vagrant failed to build

**Comment by kseidenschnur** [comment]
Hi,

can you please make sure that the ansible extension is installed by executing following command: ansible-galaxy collection install community.windows
Please make sure that you are in the correct environment.

You could also try to execute the deploy script again, this will also make sure that all dependencies are available.
