### ISSUE TITLE
Caldera Elevated Agents Keep Failing.

### ISSUE THREAD

**Issue by jaco-za** [splunk/attack_range_local#42]
I've tried different deployment variations of Attack Range Local, and it seems Elevated agents in Caldera keeps on failing.

VM setups I've tried:
- Ubuntu 20.04 Physical Host, with Attack Range installed directly on it using Virtualbox.
- Windows 10 Host Physical Host, with a Ubuntu 18.04 Guest running in VMware on which Attack Range local is then installed using Virtualbox.

I've tried different windows hosts, and have deleted rebuilt etc a few times.

Everything else works as expected. I.e. Splunk, Caldera in general etc, but Elevated agents show up, and then goes offline after a while.

If an operation is run while an Elevated agent is still live, it shows a red cross in the Operations tab for that agents job, and the message "Internal Server Error".

Operations using User level agents runs as expected.

I'm not sure though if this is due to the local Attack Range variant, or if this is a Caldera issue?

**Comment by P4T12ICK** [comment]
We had a lot of problems with the stability of Caldera. We follow the installation guidelines. Therefore, I assume it's something with Caldera. Can you open an issue in their project? Thank you.

**Comment by jaco-za** [comment]
Will do, thanks.
