### ISSUE TITLE
Enhancement: support for vmware workstation

### ISSUE THREAD

**Issue by dagar741** [splunk/attack_range_local#44]
I have other VMs that only work with vmware (and not virtualbox) that I would like to interact with Attack Range.

**Comment by pyth0n1c** [comment]
Closing this issue as Attack Range Local has been deprecated (and functionality migrated into Attack Range).  Please use [https://github.com/splunk/attack_range](https://github.com/splunk/attack_range) for all future simulation needs.  If this continues to be an issue, please open a ticket in that repo.
