### ISSUE TITLE
Failed to join domain

### ISSUE THREAD

**Issue by Stef107** [splunk/attack_range_local#45]
I found the windows_client machine cannot join domain because the powershell script is not adapted to NonInteractive mode.

https://github.com/splunk/attack_range_local/blob/master/ansible/roles/windows_domain_client/files/join_domain.ps1

Just need to add **"Force"** option for Add-Computer command.

`Add-Computer -DomainName $domain -Credential $credential -Force`

**Comment by pyth0n1c** [comment]
Closing this issue as Attack Range Local has been deprecated (and functionality migrated into Attack Range).  Please use [https://github.com/splunk/attack_range](https://github.com/splunk/attack_range) for all future simulation needs.  If this continues to be an issue, please open a ticket in that repo.
