### ISSUE TITLE
win_dns_client setting is applied for the NAT adapter

### ISSUE THREAD

**Issue by Stef107** [splunk/attack_range_local#46]
The default tasks set dns ip address on the NAT adapter of windows_client machine, "ansible_interfaces.0.connection_name".
https://github.com/splunk/attack_range_local/blob/master/ansible/roles/windows_domain_client/tasks/create.yml

I think the dns ip should be applied for the host-only adapter, because "windows_domain_controller_private_ip" is local network ip address.
(The host-only adapter name is "ansible_interfaces.1.connection_name".)

**Comment by pyth0n1c** [comment]
Closing this issue as Attack Range Local has been deprecated (and functionality migrated into Attack Range).  Please use [https://github.com/splunk/attack_range](https://github.com/splunk/attack_range) for all future simulation needs.  If this continues to be an issue, please open a ticket in that repo.
