### ISSUE TITLE
Attack range local will not build all boxes on macOS Big Sur.

### ISSUE THREAD

**Issue by s1nglethr3ad** [splunk/attack_range_local#47]
I have enabled the boxes in attack_range_local.conf.  I am currently on macOS Big Sur 11.6.  The only boxes that will build are the Splunk server and the domain controller.  I am on an Intel chip and have plenty of RAM.

**Comment by pyth0n1c** [comment]
Closing this issue as Attack Range Local has been deprecated (and functionality migrated into Attack Range).  Please use [https://github.com/splunk/attack_range](https://github.com/splunk/attack_range) for all future simulation needs.  If this continues to be an issue, please open a ticket in that repo.
