### ISSUE TITLE
Couldn't resolve module/action 'community.windows.win_timezone' while deploying...

### ISSUE THREAD

**Issue by gittmer** [splunk/attack_range_local#48]
ERROR! couldn't resolve module/action 'community.windows.win_timezone'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/opt/attack_range_local/ansible/roles/windows_common/tasks/set-timezone.yml': line 1, column 3, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Set timezone to 'GMT Standard Time' (GMT)
  ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again._

Any ideas how to fix? I already tried to change the config file from this:

- name: Set timezone
  community.windows.win_timezone:
    timezone: "{{ win_timezone }}"

..to this:

- name: Set timezone to 'GMT Standard Time' (GMT)
  community.windows.win_timezone:
    timezone: "GMT Standard Time"

..but still same issue.

Thank you for your help.

**Comment by pyth0n1c** [comment]
Closing this issue as Attack Range Local has been deprecated (and functionality migrated into Attack Range).  Please use [https://github.com/splunk/attack_range](https://github.com/splunk/attack_range) for all future simulation needs.  If this continues to be an issue, please open a ticket in that repo.
