### ISSUE TITLE
Issues installing local range

### ISSUE THREAD

**Issue by antmar904** [splunk/attack_range_local#49]
Hi

I have Ubuntu 18.04 installed, dl the files and I'm trying to run "python attack_range_local.py -a build".

Here is the error I am getting:

**_"Traceback (most recent call last):
  File "attack_range_local.py", line 4, in <module>
    from modules import logger
ImportError: No module named modules"_**

**Comment by lmpro** [comment]
facing same issue. How have you solved it ?

**Comment by mikecjudge** [comment]
Any solution given for this?
