### ISSUE TITLE
Vagrant module has no attribute Issue

### ISSUE THREAD

**Issue by Lavisha97** [splunk/attack_range_local#50]
Issue: AttributeError: module 'vagrant' has no attribute 'Vagrant'
I have faced this issue multiple times if I leave the created virtual machine running and it terminates or the system turns off.
After this whichever command you try you would face the issue. Tried debugging it but it doesn't solve in any way.

Please help out on this:
![image](https://user-images.githubusercontent.com/32261530/147644722-f5813fe6-2525-42b2-97b8-9c6758a7ee35.png)

**Comment by pyth0n1c** [comment]
Closing this issue as Attack Range Local has been deprecated (and functionality migrated into Attack Range).  Please use [https://github.com/splunk/attack_range](https://github.com/splunk/attack_range) for all future simulation needs.  If this continues to be an issue, please open a ticket in that repo.
