### ISSUE TITLE
Attack range local not bulding after destroy - Ubuntu 18.04

### ISSUE THREAD

**Issue by HackeXPlorer** [splunk/attack_range_local#51]
Hi 
i installed attack range local on Ubuntu 18.04 and it worked fine, i changed the configuration file to add a windows client and  after i destroyed the current range the and try to rebuild the range, but the setup process stops after configuring the spunk VM displaying a **vagrant error.**

1) I tried to re download the git and configure. -didn't  work 
2) Uninstalled and reinstall the requirements. -didn't  work.
3) Reinstalled the host OS (ubuntu 18) and tried again and the setup process and it only worked once, after destroying the range i got the same  error below.

Error: 
 _1: from /usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/provisioners/ansible/provisioner/host.rb:179:in `execute_ansible_playbook_from_host'
/usr/share/rubygems-integration/all/gems/vagrant-2.0.2/plugins/provisioners/ansible/provisioner/host.rb:104:in `execute_command_from_host': Ansible failed to complete successfully. Any error output should be (VagrantPlugins::Ansible::Errors::AnsibleCommandFailed)
visible above. Please fix these errors and try again.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again._

![Screenshot from 2022-02-12 17-51-31](https://user-images.githubusercontent.com/69985064/153714083-9b5f51ee-c74f-4268-af7d-5e65a08dfaeb.png)

**Comment by pyth0n1c** [comment]
Closing this issue as Attack Range Local has been deprecated (and functionality migrated into Attack Range).  Please use [https://github.com/splunk/attack_range](https://github.com/splunk/attack_range) for all future simulation needs.  If this continues to be an issue, please open a ticket in that repo.
