### ISSUE TITLE
error in loading splunk

### ISSUE THREAD

**Issue by johnncennaa** [splunk/attack_range_local#53]
howdy,

trying to build the environment locally from my MacOS and am getting the following error:

fatal: [attack-range-splunk-server]: FAILED! => {"changed": false, "msg": "Could not find the requested service splunk: host"}

- I have restarted the virtualbox service
- installed/reinstalled virtualbox

still haven't came across a solution. do you know the way forward?

Thanks!

**Comment by pyth0n1c** [comment]
Closing this issue as Attack Range Local has been deprecated (and functionality migrated into Attack Range).  Please use [https://github.com/splunk/attack_range](https://github.com/splunk/attack_range) for all future simulation needs.  If this continues to be an issue, please open a ticket in that repo.
