### ISSUE TITLE
DNS fail downloading Windows UF

### ISSUE THREAD

**Issue by blackbart1269** [splunk/attack_range_local#9]
The Windows DC cannot resolve DNS.

TASK [windows_universal_forwarder : Download Splunk UF from Splunk website] ****
fatal: [attack-range-windows-domain-controller]: FAILED! => {"changed": true, "cmd": "[Net.ServicePointManager]::SecurityProtocol = \"tls12, tls11, tls\"\n(New-Object System.Net.WebClient).DownloadFile(\"https://download.splunk.com/products/universalforwarder/releases/8.0.2/windows/splunkforwarder-8.0.2-a7f645ddaf91-x64-release.msi\", \"C:\\splunkuf.msi\")", "delta": "0:00:06.203879", "end": "2020-09-28 05:42:52.751918", "msg": "non-zero return code", "rc": 1, "start": "2020-09-28 05:42:46.548039", "stderr": "Exception calling \"DownloadFile\" with \"2\" argument(s): \"The remote name could not be resolved: 'download.splunk.com'\"\r\nAt line:2 char:1\r\n+ (New-Object System.Net.WebClient).DownloadFile(\"https://download.splu ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException\r\n    + FullyQualifiedErrorId : WebException", "stderr_lines": ["Exception calling \"DownloadFile\" with \"2\" argument(s): \"The remote name could not be resolved: 'download.splunk.com'\"", "At line:2 char:1", "+ (New-Object System.Net.WebClient).DownloadFile(\"https://download.splu ...", "+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~", "    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException", "    + FullyQualifiedErrorId : WebException"], "stdout": "", "stdout_lines": []}

**Comment by P4T12ICK** [comment]
This should be fixed
